[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "google_firebase_project"
version = "0.1.0"
dependencies = [
    "python-dotenv",
    # other dependencies
]

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests*"]
